version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.16.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - forms-npm-{{ checksum "package-lock.json" }}
            - forms-npm
      - run: npm ci
      - save_cache:
          key: forms-npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run: npm run lint
      - run: npm run test
      - run:
          command: npm run e2e
          environment:
            CYPRESS_VIDEO: false

workflows:
  build:
    jobs:
      - test
